import { ReleaseRun, TimelineEvent, WorkflowNode } from './types'

export const MOCK_WORKFLOW_NODES: WorkflowNode[] = [
  {
    id: 'build',
    type: 'build',
    label: 'Build',
    status: 'success',
    startedAt: new Date(Date.now() - 15 * 60 * 1000),
    completedAt: new Date(Date.now() - 10 * 60 * 1000),
    duration: 5 * 60,
    dependencies: [],
  },
  {
    id: 'unit-tests',
    type: 'test',
    label: 'Unit Tests',
    status: 'success',
    startedAt: new Date(Date.now() - 10 * 60 * 1000),
    completedAt: new Date(Date.now() - 8 * 60 * 1000),
    duration: 2 * 60,
    dependencies: ['build'],
  },
  {
    id: 'integration-tests',
    type: 'test',
    label: 'Integration Tests',
    status: 'running',
    startedAt: new Date(Date.now() - 8 * 60 * 1000),
    duration: 1 * 60,
    dependencies: ['build'],
  },
  {
    id: 'security-scan',
    type: 'security',
    label: 'Security Scan',
    status: 'success',
    startedAt: new Date(Date.now() - 8 * 60 * 1000),
    completedAt: new Date(Date.now() - 5 * 60 * 1000),
    duration: 3 * 60,
    dependencies: ['build'],
  },
  {
    id: 'approval',
    type: 'approval',
    label: 'Approval',
    status: 'waiting',
    dependencies: ['unit-tests', 'security-scan'],
  },
  {
    id: 'db-migration',
    type: 'migration',
    label: 'DB Migration',
    status: 'pending',
    dependencies: ['approval'],
  },
  {
    id: 'deploy-staging',
    type: 'staging',
    label: 'Deploy to Staging',
    status: 'pending',
    dependencies: ['approval', 'integration-tests'],
  },
  {
    id: 'canary-deploy',
    type: 'canary',
    label: 'Canary Deploy',
    status: 'pending',
    dependencies: ['deploy-staging'],
  },
  {
    id: 'prod-deploy',
    type: 'production',
    label: 'Deploy to Production',
    status: 'pending',
    dependencies: ['canary-deploy'],
  },
]

export const MOCK_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: '1',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    type: 'node_started',
    nodeId: 'build',
    nodeName: 'Build',
    message: 'Build started',
    severity: 'info',
  },
  {
    id: '2',
    timestamp: new Date(Date.now() - 10 * 60 * 1000),
    type: 'node_completed',
    nodeId: 'build',
    nodeName: 'Build',
    message: 'Build completed successfully',
    severity: 'info',
  },
  {
    id: '3',
    timestamp: new Date(Date.now() - 10 * 60 * 1000),
    type: 'node_started',
    nodeId: 'unit-tests',
    nodeName: 'Unit Tests',
    message: 'Unit tests started',
    severity: 'info',
  },
  {
    id: '4',
    timestamp: new Date(Date.now() - 8 * 60 * 1000),
    type: 'node_completed',
    nodeId: 'unit-tests',
    nodeName: 'Unit Tests',
    message: 'Unit tests passed',
    severity: 'info',
  },
  {
    id: '5',
    timestamp: new Date(Date.now() - 8 * 60 * 1000),
    type: 'node_started',
    nodeId: 'integration-tests',
    nodeName: 'Integration Tests',
    message: 'Integration tests started',
    severity: 'info',
  },
  {
    id: '6',
    timestamp: new Date(Date.now() - 8 * 60 * 1000),
    type: 'node_started',
    nodeId: 'security-scan',
    nodeName: 'Security Scan',
    message: 'Security scan started',
    severity: 'info',
  },
  {
    id: '7',
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
    type: 'node_completed',
    nodeId: 'security-scan',
    nodeName: 'Security Scan',
    message: 'Security scan completed - no vulnerabilities found',
    severity: 'info',
  },
]

export const MOCK_RELEASE_RUN: ReleaseRun = {
  id: 'run-001',
  projectId: 'proj-001',
  projectName: 'API Service',
  branchName: 'main',
  commitHash: 'abc123def456',
  commitMessage: 'Fix: Critical bug in payment processing',
  environment: 'production',
  verdict: 'WARN',
  startedAt: new Date(Date.now() - 15 * 60 * 1000),
  updatedAt: new Date(),
  nodes: MOCK_WORKFLOW_NODES,
  failedChecks: [],
  blockedChecks: [],
  waitingChecks: ['approval'],
}
